import Head from 'next/head';

export default function Home() {
    return (
        <div>
            <Head>
                <title>NextEvents - Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <div>Lets Start</div>
        </div>
    );
}
