import Head from 'next/head';
import { Fragment } from 'react';
import EventList from '../components/Events/EventList';

function Home({ allEvents }) {
	return (
		<Fragment>
			<Head>
				<title>NextEvents - Home</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<EventList items={allEvents} />
		</Fragment>
	);
}

export const getStaticProps = async () => {
	const response = await fetch('https://database-for-projects-f2951-default-rtdb.firebaseio.com/events.json');
	const data = await response.json();

	let events = [];
	for (let [key, value] of Object.entries(data)) {
		events.push({
			id: key,
			...value,
		});
	}

	return {
		props: {
			allEvents: events,
		},
	};
};

export default Home;
